plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.54'
}

version = mod_version
group = 'com.valorcraft.vauction'

base {
    archivesName = 'VAuction-1.20.1'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
    withSourcesJar()
}

minecraft {
    mappings channel: 'official', version: minecraft_version
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods { vauction { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods { vauction { source sourceSets.main } }
        }
    }
}

repositories {
    mavenCentral()
    flatDir { dirs providers.gradleProperty('veconomy_dir').orElse('../VEconomy/build/libs').get() }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    compileOnly fg.deobf(group: 'local', name: 'VEconomy-1.20.1', version: '1.0.0')
    runtimeOnly fg.deobf(group: 'local', name: 'VEconomy-1.20.1', version: '1.0.0', classifier: 'all')
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testImplementation 'org.xerial:sqlite-jdbc:3.45.3.0'
}

test { useJUnitPlatform() }

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand version: project.version }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

jar {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
    manifest {
        attributes([
                'Specification-Title': 'VAuction',
                'Specification-Version': project.version,
                'Specification-Vendor': 'ValorCraft',
                'Implementation-Title': 'VAuction',
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor': 'ValorCraft'
        ])
    }
    finalizedBy 'reobfJar'
}
